import mongoose from 'mongoose';

const MetaAccountCacheSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  metaAccountId: {
    type: String,
    required: true,
    index: true
  },
  businessId: {
    type: String,
    required: true
  },
  // COMPLETE ACCOUNT DATA - Everything Meta has
  accountData: {
    // Basic account info
    account_id: String,
    name: String,
    account_status: Number,
    age: Number,
    amount_spent: String,
    balance: String,
    business_country_code: String,
    currency: String,
    timezone_name: String,
    timezone_offset_hours_utc: Number,

    // Capabilities and features
    capabilities: [String],
    can_create_brand_lift_study: Boolean,
    created_time: Date,
    end_advertiser_name: String,
    funding_source: String,
    has_migrated_permissions: Boolean,
    io_number: String,
    is_attribution_spec_system_default: Boolean,
    is_direct_deals_enabled: Boolean,
    is_in_3ds_authorization_enabled_market: Boolean,
    is_notifications_enabled: Boolean,
    is_personal: Number,
    is_prepay_account: Boolean,
    is_tax_id_required: Boolean,
    line_numbers: [Number],
    media_agency: String,
    min_campaign_group_spend_cap: String,
    min_daily_budget: Number,
    owner: String,
    partner: String,
    rf_spec: mongoose.Schema.Types.Mixed,
    show_checkout_experience: Boolean,
    spend_cap: String,
    tax_id: String,
    tax_id_status: Number,
    tax_id_type: String,
    user_access_expire_time: Date,
    user_role: String
  },

  // COMPLETE CAMPAIGNS DATA
  campaigns: [{
    id: String,
    account_id: String,
    adlabels: [mongoose.Schema.Types.Mixed],
    bid_strategy: String,
    boosted_object_id: String,
    brand_lift_studies: [mongoose.Schema.Types.Mixed],
    budget_rebalance_flag: Boolean,
    budget_remaining: String,
    buying_type: String,
    can_create_brand_lift_study: Boolean,
    can_use_spend_cap: Boolean,
    configured_status: String,
    created_time: Date,
    daily_budget: String,
    effective_status: String,
    issues_info: [mongoose.Schema.Types.Mixed],
    last_budget_toggling_time: Date,
    lifetime_budget: String,
    name: String,
    objective: String,
    pacing_type: [String],
    promoted_object: mongoose.Schema.Types.Mixed,
    recommendations: [mongoose.Schema.Types.Mixed],
    source_campaign: mongoose.Schema.Types.Mixed,
    source_campaign_id: String,
    special_ad_categories: [String],
    special_ad_category_country: [String],
    spend_cap: String,
    start_time: Date,
    status: String,
    stop_time: Date,
    topline_id: String,
    updated_time: Date
  }],

  // COMPLETE AD SETS DATA
  adsets: [{
    id: String,
    account_id: String,
    adlabels: [mongoose.Schema.Types.Mixed],
    adset_schedule: [mongoose.Schema.Types.Mixed],
    asset_feed_id: String,
    attribution_spec: [mongoose.Schema.Types.Mixed],
    bid_adjustments: mongoose.Schema.Types.Mixed,
    bid_amount: Number,
    bid_constraints: mongoose.Schema.Types.Mixed,
    bid_info: mongoose.Schema.Types.Mixed,
    bid_strategy: String,
    billing_event: String,
    budget_remaining: String,
    campaign: mongoose.Schema.Types.Mixed,
    campaign_id: String,
    configured_status: String,
    created_time: Date,
    creative_sequence: [String],
    daily_budget: String,
    daily_min_spend_target: String,
    daily_spend_cap: String,
    destination_type: String,
    effective_status: String,
    end_time: Date,
    frequency_control_specs: [mongoose.Schema.Types.Mixed],
    full_funnel_exploration_mode: String,
    instagram_actor_id: String,
    is_dynamic_creative: Boolean,
    issues_info: [mongoose.Schema.Types.Mixed],
    learning_stage_info: mongoose.Schema.Types.Mixed,
    lifetime_budget: String,
    lifetime_imps: Number,
    lifetime_min_spend_target: String,
    lifetime_spend_cap: String,
    multi_optimization_goal_weight: String,
    name: String,
    optimization_goal: String,
    optimization_sub_event: String,
    pacing_type: [String],
    promoted_object: mongoose.Schema.Types.Mixed,
    recommendations: [mongoose.Schema.Types.Mixed],
    recurring_budget_semantics: Boolean,
    review_feedback: String,
    rf_prediction_id: String,
    source_adset: mongoose.Schema.Types.Mixed,
    source_adset_id: String,
    start_time: Date,
    status: String,
    targeting: mongoose.Schema.Types.Mixed, // COMPLETE targeting data
    time_based_ad_rotation_id_blocks: [[Number]],
    time_based_ad_rotation_intervals: [Number],
    updated_time: Date,
    use_new_app_click: Boolean
  }],

  // COMPLETE ADS DATA
  ads: [{
    id: String,
    account_id: String,
    ad_review_feedback: mongoose.Schema.Types.Mixed,
    adlabels: [mongoose.Schema.Types.Mixed],
    adset: mongoose.Schema.Types.Mixed,
    adset_id: String,
    bid_amount: Number,
    bid_info: mongoose.Schema.Types.Mixed,
    bid_type: String,
    campaign: mongoose.Schema.Types.Mixed,
    campaign_id: String,
    configured_status: String,
    conversion_specs: [mongoose.Schema.Types.Mixed],
    created_time: Date,
    creative: mongoose.Schema.Types.Mixed, // COMPLETE creative data
    demolink_hash: String,
    display_sequence: Number,
    effective_status: String,
    engagement_audience: Boolean,
    failed_delivery_checks: [mongoose.Schema.Types.Mixed],
    issues_info: [mongoose.Schema.Types.Mixed],
    last_updated_by_app_id: String,
    name: String,
    preview_shareable_link: String,
    priority: Number,
    recommendations: [mongoose.Schema.Types.Mixed],
    source_ad: mongoose.Schema.Types.Mixed,
    source_ad_id: String,
    status: String,
    tracking_specs: [mongoose.Schema.Types.Mixed],
    updated_time: Date
  }],

  // COMPLETE INSIGHTS DATA (Last 90 days)
  insights: [{
    account_currency: String,
    account_id: String,
    account_name: String,
    action_values: [mongoose.Schema.Types.Mixed],
    actions: [mongoose.Schema.Types.Mixed],
    ad_click_actions: [mongoose.Schema.Types.Mixed],
    ad_impression_actions: [mongoose.Schema.Types.Mixed],
    age_targeting: String,
    attribution_setting: String,
    auction_bid: String,
    auction_competitiveness: String,
    auction_max_competitor_bid: String,
    buying_type: String,
    campaign_id: String,
    campaign_name: String,
    canvas_avg_view_percent: String,
    canvas_avg_view_time: String,
    catalog_segment_actions: [mongoose.Schema.Types.Mixed],
    catalog_segment_value: [mongoose.Schema.Types.Mixed],
    clicks: String,
    conversion_rate_ranking: String,
    conversion_values: [mongoose.Schema.Types.Mixed],
    conversions: [mongoose.Schema.Types.Mixed],
    converted_product_quantity: [mongoose.Schema.Types.Mixed],
    converted_product_value: [mongoose.Schema.Types.Mixed],
    cost_per_15_sec_video_view: [mongoose.Schema.Types.Mixed],
    cost_per_2_sec_continuous_video_view: [mongoose.Schema.Types.Mixed],
    cost_per_action_type: [mongoose.Schema.Types.Mixed],
    cost_per_ad_click: [mongoose.Schema.Types.Mixed],
    cost_per_conversion: [mongoose.Schema.Types.Mixed],
    cost_per_dda_countby_convs: String,
    cost_per_inline_link_click: String,
    cost_per_inline_post_engagement: String,
    cost_per_one_thousand_ad_impression: [mongoose.Schema.Types.Mixed],
    cost_per_outbound_click: [mongoose.Schema.Types.Mixed],
    cost_per_thruplay: [mongoose.Schema.Types.Mixed],
    cost_per_unique_action_type: [mongoose.Schema.Types.Mixed],
    cost_per_unique_click: String,
    cost_per_unique_conversion: [mongoose.Schema.Types.Mixed],
    cost_per_unique_inline_link_click: String,
    cost_per_unique_outbound_click: [mongoose.Schema.Types.Mixed],
    cpc: String,
    cpm: String,
    cpp: String,
    created_time: Date,
    ctr: String,
    date_start: String,
    date_stop: String,
    dda_countby_convs: String,
    engagement_rate_ranking: String,
    estimated_ad_recall_rate: String,
    estimated_ad_recall_rate_lower_bound: String,
    estimated_ad_recall_rate_upper_bound: String,
    estimated_ad_recallers: String,
    estimated_ad_recallers_lower_bound: String,
    estimated_ad_recallers_upper_bound: String,
    frequency: String,
    full_view_impressions: String,
    full_view_reach: String,
    gender_targeting: String,
    impressions: String,
    inline_link_click_ctr: String,
    inline_link_clicks: String,
    inline_post_engagement: String,
    instant_experience_clicks_to_open: String,
    instant_experience_clicks_to_start: String,
    instant_experience_outbound_clicks: [mongoose.Schema.Types.Mixed],
    interactive_component_tap: [mongoose.Schema.Types.Mixed],
    labels: String,
    location: [mongoose.Schema.Types.Mixed],
    mobile_app_purchase_roas: [mongoose.Schema.Types.Mixed],
    objective: String,
    optimization_goal: String,
    outbound_clicks: [mongoose.Schema.Types.Mixed],
    outbound_clicks_ctr: [mongoose.Schema.Types.Mixed],
    place_page_name: String,
    placement: String,
    platform_position: String,
    product_id: String,
    publisher_platform: String,
    purchase_roas: [mongoose.Schema.Types.Mixed],
    quality_ranking: String,
    reach: String,
    region: String,
    relevance_score: mongoose.Schema.Types.Mixed,
    rule_asset: [mongoose.Schema.Types.Mixed],
    social_spend: String,
    spend: String,
    total_postbacks: String,
    total_postbacks_detailed: [mongoose.Schema.Types.Mixed],
    unique_actions: [mongoose.Schema.Types.Mixed],
    unique_clicks: String,
    unique_conversions: [mongoose.Schema.Types.Mixed],
    unique_ctr: String,
    unique_inline_link_click_ctr: String,
    unique_inline_link_clicks: String,
    unique_link_clicks_ctr: String,
    unique_outbound_clicks: [mongoose.Schema.Types.Mixed],
    unique_outbound_clicks_ctr: [mongoose.Schema.Types.Mixed],
    unique_video_continuous_2_sec_watched_actions: [mongoose.Schema.Types.Mixed],
    unique_video_view_15_sec: [mongoose.Schema.Types.Mixed],
    updated_time: Date,
    video_15_sec_watched_actions: [mongoose.Schema.Types.Mixed],
    video_30_sec_watched_actions: [mongoose.Schema.Types.Mixed],
    video_avg_time_watched_actions: [mongoose.Schema.Types.Mixed],
    video_continuous_2_sec_watched_actions: [mongoose.Schema.Types.Mixed],
    video_p100_watched_actions: [mongoose.Schema.Types.Mixed],
    video_p25_watched_actions: [mongoose.Schema.Types.Mixed],
    video_p50_watched_actions: [mongoose.Schema.Types.Mixed],
    video_p75_watched_actions: [mongoose.Schema.Types.Mixed],
    video_p95_watched_actions: [mongoose.Schema.Types.Mixed],
    video_play_actions: [mongoose.Schema.Types.Mixed],
    video_play_curve_actions: [mongoose.Schema.Types.Mixed],
    video_play_retention_0_to_15s_actions: [mongoose.Schema.Types.Mixed],
    video_play_retention_20_to_60s_actions: [mongoose.Schema.Types.Mixed],
    video_play_retention_graph_actions: [mongoose.Schema.Types.Mixed],
    video_thruplay_watched_actions: [mongoose.Schema.Types.Mixed],
    video_time_watched_actions: [mongoose.Schema.Types.Mixed],
    website_ctr: [mongoose.Schema.Types.Mixed],
    website_purchase_roas: [mongoose.Schema.Types.Mixed]
  }],

  // NEW: PLACEMENT BREAKDOWNS (Expert Logic)
  placementInsights: [{
    date_start: String,
    date_stop: String,
    publisher_platform: String,
    platform_position: String,
    device_platform: String,
    impression_device: String,
    spending: Number,
    impressions: Number,
    clicks: Number,
    ctr: Number,
    cpc: Number,
    cpm: Number,
    reach: Number,
    actions: [mongoose.Schema.Types.Mixed]
  }],

  // NEW: DEMOGRAPHIC BREAKDOWNS (Expert Logic)
  demographicInsights: [{
    date_start: String,
    date_stop: String,
    age: String,
    gender: String,
    spending: Number,
    impressions: Number,
    clicks: Number,
    ctr: Number,
    cpc: Number,
    cpm: Number,
    reach: Number,
    actions: [mongoose.Schema.Types.Mixed]
  }],

  // COMPLETE CUSTOM AUDIENCES DATA
  customAudiences: [{
    id: String,
    account_id: String,
    approximate_count_lower_bound: Number,
    approximate_count_upper_bound: Number,
    customer_file_source: String,
    data_source: mongoose.Schema.Types.Mixed,
    data_source_types: String,
    datafile_custom_audience_uploading_status: String,
    delete_time: Number,
    delivery_status: mongoose.Schema.Types.Mixed,
    description: String,
    excluded_custom_audiences: [mongoose.Schema.Types.Mixed],
    external_event_source: mongoose.Schema.Types.Mixed,
    household_audience: Number,
    included_custom_audiences: [mongoose.Schema.Types.Mixed],
    is_household: Boolean,
    is_snapshot: Boolean,
    is_value_based: Boolean,
    lookalike_audience_ids: [String],
    lookalike_spec: mongoose.Schema.Types.Mixed,
    name: String,
    operation_status: mongoose.Schema.Types.Mixed,
    opt_out_link: String,
    owner_business: mongoose.Schema.Types.Mixed,
    page_deletion_marked_delete_time: Number,
    permission_for_actions: mongoose.Schema.Types.Mixed,
    pixel_id: String,
    regulated_audience_spec: mongoose.Schema.Types.Mixed,
    retention_days: Number,
    rev_share_policy_id: Number,
    rule: mongoose.Schema.Types.Mixed,
    rule_aggregation: String,
    rule_v2: mongoose.Schema.Types.Mixed,
    seed_audience: Number,
    sharing_status: mongoose.Schema.Types.Mixed,
    subtype: String,
    time_content_updated: Number,
    time_created: Number,
    time_updated: Number
  }],

  // COMPLETE PIXELS DATA
  pixels: [{
    id: String,
    automatic_matching_fields: [String],
    can_proxy: Boolean,
    code: String,
    creation_time: Date,
    creator: mongoose.Schema.Types.Mixed,
    data_use_setting: String,
    description: String,
    duplicate_entries: Number,
    enable_auto_assign_to_accounts: Boolean,
    enable_automatic_matching: Boolean,
    event_stats: String,
    event_time_max: Number,
    event_time_min: Number,
    first_party_cookie_status: String,
    has_1p_pixel_domain: Boolean,
    is_consolidated_container: Boolean,
    is_created_by_business: Boolean,
    is_crm: Boolean,
    is_mta_use: Boolean,
    is_restricted_use: Boolean,
    is_unavailable: Boolean,
    last_fired_time: Date,
    last_upload_app: mongoose.Schema.Types.Mixed,
    last_upload_app_changed_time: Number,
    match_rate_approx: Number,
    matched_entries: Number,
    name: String,
    owner_ad_account: mongoose.Schema.Types.Mixed,
    owner_business: mongoose.Schema.Types.Mixed,
    usage: mongoose.Schema.Types.Mixed,
    user_access_expire_time: Date,
    valid_entries: Number
  }],

  // Cache metadata
  lastUpdated: {
    type: Date,
    default: Date.now
  },
  cacheVersion: {
    type: String,
    default: '1.0'
  },
  timePeriod: {
    type: String,
    enum: ['last_30_days', 'last_90_days', 'last_6_months', 'last_year', 'last_2_years', 'last_5_years', 'all_time'],
    default: 'last_90_days'
  },
  insightsDateRange: {
    startDate: Date,
    endDate: Date
  },
  isComplete: {
    type: Boolean,
    default: false
  },
  syncStatus: {
    type: String,
    enum: ['pending', 'syncing', 'completed', 'failed'],
    default: 'pending'
  },
  syncErrors: [String]
}, {
  timestamps: true
});

// Compound indexes for fast queries
MetaAccountCacheSchema.index({ userId: 1, metaAccountId: 1 }, { unique: true });
MetaAccountCacheSchema.index({ lastUpdated: 1 });
MetaAccountCacheSchema.index({ syncStatus: 1 });

export default mongoose.models.MetaAccountCache || mongoose.model('MetaAccountCache', MetaAccountCacheSchema);